function S=manual_selection(temp,img1,img2,img3,sel_prob,sel_temp,idx2,idx3)

S = struct('First',1);
S.str=[45 55 45];
tol=.01;
S.firstPrint=1;
S.skip=0;
S.idx2=idx2;
S.idx3=idx3;
S.select=[0 0 0];

network_names={'Dorsal Attention','Auditory','Basal Ganglia','Cerebellum','Cognition/Emotion',...
    'Default Mode, Dorsal/Posterior','Default Mode, Medial','Executive Control','Frontoparietal, Left',...
    'Frontoparietal, Right','Ventral Stream, Left','Ventral Stream, Right','Postcentral','Precentral',...
    'Precuneus','Salience','Sensorimotor','Visual, Primary I','Visual, Primary II','Visual, Medial',...
    'Visual, Higher Level'};

handles_gui.h = figure;
scr_dim=get(0, 'ScreenSize');

set(handles_gui.h, ...
    'position', scr_dim, ...
    'name', 'Manual selection', ...
    'tag', 'h');

uicontrol('style', 'pushbutton', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.85 .05 .05 .035], ...
    'FontSize', 12*scr_dim(4)/1080,...
    'callback', {@skip_press},...
    'value',0,...
    'string', 'Skip');
uicontrol('style', 'pushbutton', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.9 .05 .05 .035], ...
    'FontSize', 12*scr_dim(4)/1080,...
    'FontWeight', 'bold',...
    'Enable', 'off',...
    'Tag','next',...
    'callback', {@next_press},...
    'string', 'Next');

S.tmp=temp;
S.tmp(S.tmp==0)=nan;

S.img1=img1;
S.img1(abs(S.img1)<tol)=nan;

S.img2=img2;
S.img2(abs(S.img2)<tol)=nan;

S.img3=img3;
S.img3(abs(S.img3)<tol)=nan;

hp1 = uipanel('Title','Template',...
    'FontSize',12*scr_dim(4)/1080,...
    'BackgroundColor',[.85 .85 .85],...
    'Position',[.05 .1 .2 .8],...
    'Tag','TmpPanel',...
    'Clipping','on');
uicontrol('style', 'text', ...
    'Parent',hp1,...
    'BackgroundColor', [0.85 0.85 0.85],...
    'units', 'normalized',...
    'position', [.02 .02 .96 .05], ...
    'FontSize', 11*scr_dim(4)/1080,...
    'FontWeight', 'bold',...
    'ForegroundColor', 'blue',...
    'string', ['RSN to be defined: ' char(network_names(sel_temp))]);

hp2 = uipanel('Title','Component #1',...
    'FontSize',12*scr_dim(4)/1080,...
    'BackgroundColor',[.85 .85 .85],...
    'Position',[.31 .1 .2 .8],...
    'Tag','img1Panel',...
    'Clipping','on');
A0 = axes;
set(A0,'Parent',hp2,...
    'NextPlot', 'replacechildren');
uicontrol('style', 'text', ...
    'Parent',hp2,...
    'BackgroundColor', [0.85 0.85 0.85],...
    'units', 'normalized',...
    'position', [.02 .02 .96 .05], ...
    'FontSize', 13*scr_dim(4)/1080,...
    'FontWeight', 'bold',...
    'ForegroundColor', 'red',...
    'tag', 'prob1',...
    'string', ['probability = ' num2str(sel_prob(1), '%01.f') '%']);
uicontrol('style', 'pushbutton', ...
    'Parent',hp2,...
    'units', 'normalized',...
    'position', [.4 .95 .2 .03], ...
    'FontSize', 12*scr_dim(4)/1080,...
    'FontWeight', 'bold',...
    'callback', {@select1_press},...
    'tag', 'select1',...
    'string', 'Select');

if S.idx2~=0

hp3 = uipanel('Title','Component #2',...
    'FontSize',12*scr_dim(4)/1080,...
    'BackgroundColor',[.85 .85 .85],...
    'Position',[.53 .1 .2 .8],...
    'Tag','img2Panel',...
    'Clipping','on');
A0 = axes;
set(A0,'Parent',hp3,...
    'NextPlot', 'replacechildren');
uicontrol('style', 'text', ...
    'Parent',hp3,...
    'BackgroundColor', [0.85 0.85 0.85],...
    'units', 'normalized',...
    'position', [.02 .02 .96 .05], ...
    'FontSize', 13*scr_dim(4)/1080,...
    'FontWeight', 'bold',...
    'ForegroundColor', 'red',...
    'tag', 'prob2',...
    'string', ['probability = ' num2str(sel_prob(2), '%01.f') '%']);
uicontrol('style', 'pushbutton', ...
    'Parent',hp3,...
    'units', 'normalized',...
    'position', [.4 .95 .2 .03], ...
    'FontSize', 12*scr_dim(4)/1080,...
    'FontWeight', 'bold',...
    'callback', {@select2_press},...
    'tag', 'select2',...
    'string', 'Select');

end

if S.idx3~=0
    
    hp4 = uipanel('Title','Component #3',...
        'FontSize',12*scr_dim(4)/1080,...
        'BackgroundColor',[.85 .85 .85],...
        'Position',[.75 .1 .2 .8],...
        'Tag','img3Panel',...
        'Clipping','on');
    A0 = axes;
    set(A0,'Parent',hp4,...
        'NextPlot', 'replacechildren');
    uicontrol('style', 'text', ...
        'Parent',hp4,...
        'BackgroundColor', [0.85 0.85 0.85],...
        'units', 'normalized',...
        'position', [.02 .02 .96 .05], ...
        'FontSize', 13*scr_dim(4)/1080,...
        'FontWeight', 'bold',...
        'ForegroundColor', 'red',...
        'tag', 'prob3',...
        'string', ['probability = ' num2str(sel_prob(3), '%01.f') '%']);
    uicontrol('style', 'pushbutton', ...
        'Parent',hp4,...
        'units', 'normalized',...
        'position', [.4 .95 .2 .03], ...
        'FontSize', 12*scr_dim(4)/1080,...
        'FontWeight', 'bold',...
        'callback', {@select3_press},...
        'tag', 'select3',...
        'string', 'Select');
    
end

% Select x
uicontrol('style', 'text', ...
    'Parent',handles_gui.h,...
    'BackgroundColor', [0.9 0.9 0.9],...
    'units', 'normalized',...
    'position', [.78 .95 .02 .02], ...
    'string', 'x');
uicontrol('style', 'edit', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.8 .95 .02 .02], ...
    'callback', {@sliceSelect},...
    'BackgroundColor', 'white',...
    'String', num2str(S.str(1)),...
    'tag', 'SliceX');
uicontrol('style', 'slider', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.82 .95 .01 .02], ...
    'callback', {@btnSlider},...
    'Selected', 'off',...
    'Max', 91,...
    'Min', 1, ...
    'Value', 45, ...
    'SliderStep', [1/90,1/9],...
    'tag', 'SliderX');

% Select y
uicontrol('style', 'text', ...
    'Parent',handles_gui.h,...
    'BackgroundColor', [0.9 0.9 0.9],...
    'units', 'normalized',...
    'position', [.84 .95 .02 .02], ...
    'string', 'y');
uicontrol('style', 'edit', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.86 .95 .02 .02], ...
    'callback', {@sliceSelect},...
    'BackgroundColor', 'white',...
    'String', num2str(S.str(2)),...
    'tag', 'SliceY');
uicontrol('style', 'slider', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.88 .95 .01 .02], ...
    'callback', {@btnSlider},...
    'Selected', 'off',...
    'Max', 109,...
    'Min', 1, ...
    'Value', 55, ...
    'SliderStep', [1/108,1/9],...
    'tag', 'SliderY');

% Select z
uicontrol('style', 'text', ...
    'Parent',handles_gui.h,...
    'BackgroundColor', [0.9 0.9 0.9],...
    'units', 'normalized',...
    'position', [.9 .95 .02 .02], ...
    'string', 'z');
uicontrol('style', 'edit', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.92 .95 .02 .02], ...
    'callback', {@sliceSelect},...
    'BackgroundColor', 'white',...
    'String', num2str(S.str(3)),...
    'tag', 'SliceZ');
uicontrol('style', 'slider', ...
    'Parent',handles_gui.h,...
    'units', 'normalized',...
    'position', [.94 .95 .01 .02], ...
    'callback', {@btnSlider},...
    'Selected', 'off',...
    'Max', 91,...
    'Min', 1, ...
    'Value', 45, ...
    'SliderStep', [1/90,1/9],...
    'tag', 'SliderZ');

guidata(handles_gui.h, S);
print_image(S,S.idx2,S.idx3)

uiwait(handles_gui.h);
S = guidata(handles_gui.h);

close(handles_gui.h)

return

function select1_press(src, ~)
handles_gui = guihandles(src);
S = guidata(src);

if S.select(1)==0
    S.select=[1 0 0];
    
    set(handles_gui.select1, 'Selected', 'on');
    set(handles_gui.select2, 'Selected', 'off');
    set(handles_gui.select3, 'Selected', 'off');
    
    set(handles_gui.img1Panel, 'BackgroundColor', [.92 .85 .85]);
    set(handles_gui.img2Panel, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.img3Panel, 'BackgroundColor', [.85 .85 .85]);
    
    set(handles_gui.prob1, 'BackgroundColor', [.92 .85 .85]);
    set(handles_gui.prob2, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.prob3, 'BackgroundColor', [.85 .85 .85]);
    
    set(handles_gui.next, 'enable', 'on');
else
    S.select=[0 0 0];
    set(handles_gui.select1, 'Selected', 'off');
    set(handles_gui.img1Panel, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.next, 'enable', 'off');
end

guidata(handles_gui.h, S);

return

function select2_press(src, ~)
handles_gui = guihandles(src);
S = guidata(src);

if S.select(2)==0
    S.select=[0 1 0];
    
    set(handles_gui.select1, 'Selected', 'off');
    set(handles_gui.select2, 'Selected', 'on');
    set(handles_gui.select3, 'Selected', 'off');
    
    set(handles_gui.img1Panel, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.img2Panel, 'BackgroundColor', [.92 .85 .85]);
    set(handles_gui.img3Panel, 'BackgroundColor', [.85 .85 .85]);
    
    set(handles_gui.prob1, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.prob2, 'BackgroundColor', [.92 .85 .85]);
    set(handles_gui.prob3, 'BackgroundColor', [.85 .85 .85]);
    
    set(handles_gui.next, 'enable', 'on');
else
    S.select=[0 0 0];
    set(handles_gui.select2, 'Selected', 'off');
    set(handles_gui.img2Panel, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.next, 'enable', 'off');
end

guidata(handles_gui.h, S);

return

function select3_press(src, ~)
handles_gui = guihandles(src);
S = guidata(src);

if S.select(3)==0
    S.select=[0 0 1];
    
    set(handles_gui.select1, 'Selected', 'off');
    set(handles_gui.select2, 'Selected', 'off');
    set(handles_gui.select3, 'Selected', 'on');
    
    set(handles_gui.img1Panel, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.img2Panel, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.img3Panel, 'BackgroundColor', [.92 .85 .85]);
    
    set(handles_gui.prob1, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.prob2, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.prob3, 'BackgroundColor', [.92 .85 .85]);
    
    set(handles_gui.next, 'enable', 'on');
else
    S.select=[0 0 0];
    set(handles_gui.select3, 'Selected', 'off');
    set(handles_gui.img3Panel, 'BackgroundColor', [.85 .85 .85]);
    set(handles_gui.next, 'enable', 'off');
end

guidata(handles_gui.h, S);

return

function next_press(src, ~)
handles_gui = guihandles(src);
S = guidata(src);

guidata(handles_gui.h, S);
uiresume(handles_gui.h);
return

function skip_press(src, ~)
handles_gui = guihandles(src);
S = guidata(src);

S.skip=1;

guidata(handles_gui.h, S);
uiresume(handles_gui.h);
return

function btnSlider(src, ~)
handles = guihandles(src);
S = guidata(src);

coord = round(get(src,'Value'));

if strcmp(get(src,'Tag'),'SliderX')
    set(handles.SliceX, 'String', coord);
elseif strcmp(get(src,'Tag'),'SliderY')
    set(handles.SliceY, 'String', coord);
else
    set(handles.SliceZ, 'String', coord);
end

set(src,'Value', coord);
guidata(handles.h,S);
print_image(S,S.idx2,S.idx3)

return

function sliceSelect(src, ~)
handles = guihandles(src);
S = guidata(src);

slice = str2double(get(src, 'string'));

if slice<1
    slice=1;
end

if strcmp(get(src,'Tag'),'SliceX')
    if slice>get(handles.SliderX, 'Max')
        slice=get(handles.SliderX,'Max');
    end
    set(handles.SliderX, 'Value', slice);
elseif strcmp(get(src,'Tag'),'SliceY')
    if slice>get(handles.SliderY, 'Max')
        slice=get(handles.SliderY,'Max');
    end
    set(handles.SliderY, 'Value', slice);
else
    if slice>get(handles.SliderZ, 'Max')
        slice=get(handles.SliderZ,'Max');
    end
    set(handles.SliderZ, 'Value', slice);
end

set(src,'string', num2str(slice));
set(src,'Value', slice);

guidata(handles.h, S);
print_image(S,S.idx2,S.idx3)

return

function print_image(S,idx2,idx3)
handles = guihandles;

if S.firstPrint==1
    x=S.str(1);
    y=S.str(2);
    z=S.str(3);
else
    x=get(handles.SliderX,'value');
    y=get(handles.SliderY,'value');
    z=get(handles.SliderZ,'value');
end
    
axialtmp=S.tmp(:,:,z);
coronaltmp=S.tmp(:,y,:);
sagittaltmp=S.tmp(x,:,:);
Atmp=(rot90(axialtmp));
Btmp=(rot90(squeeze(coronaltmp)));
Ctmp=(rot90(squeeze(sagittaltmp)));

axial1=S.img1(:,:,z);
coronal1=S.img1(:,y,:);
sagittal1=S.img1(x,:,:);
A1=(rot90(axial1));
B1=(rot90(squeeze(coronal1)));
C1=(rot90(squeeze(sagittal1)));

axial2=S.img2(:,:,z);
coronal2=S.img2(:,y,:);
sagittal2=S.img2(x,:,:);
A2=(rot90(axial2));
B2=(rot90(squeeze(coronal2)));
C2=(rot90(squeeze(sagittal2)));

axial3=S.img3(:,:,z);
coronal3=S.img3(:,y,:);
sagittal3=S.img3(x,:,:);
A3=(rot90(axial3));
B3=(rot90(squeeze(coronal3)));
C3=(rot90(squeeze(sagittal3)));

A0 = axes;
set(A0,'Parent',handles.TmpPanel,'NextPlot', 'replacechildren');

min_tmp=min(min(min(S.tmp)));
max_tmp=max(max(max(S.tmp)));
lim0= mean([min_tmp max_tmp]);
subplot(3,1,3), imshow(Atmp)
colormap(gca, jet(256));caxis([-lim0 lim0]);
subplot(3,1,1), imshow(Btmp)
colormap(gca, jet(256));caxis([-lim0 lim0]);
subplot(3,1,2), imshow(Ctmp)
colormap(gca, jet(256));caxis([-lim0 lim0]);

A0 = axes;
set(A0,'Parent',handles.img1Panel,'NextPlot', 'replacechildren');

min_img1=min(min(min(S.img1)));
max_img1=max(max(max(S.img1)));
lim1= abs(mean([min_img1 max_img1]));
subplot(3,1,3), imshow(A1)
colormap(gca, jet(256));caxis([-lim1 lim1]);
subplot(3,1,1), imshow(B1)
colormap(gca, jet(256));caxis([-lim1 lim1]);
subplot(3,1,2), imshow(C1)
colormap(gca, jet(256));caxis([-lim1 lim1]);

if S.idx2~=0
    
    A0 = axes;
    set(A0,'Parent',handles.img2Panel,'NextPlot', 'replacechildren');
    
    min_img2=min(min(min(S.img2)));
    max_img2=max(max(max(S.img2)));
    lim2= abs(mean([min_img2 max_img2]));
    subplot(3,1,3), imshow(A2)
    colormap(gca, jet(256));caxis([-lim2 lim2]);
    subplot(3,1,1), imshow(B2)
    colormap(gca, jet(256));caxis([-lim2 lim2]);
    subplot(3,1,2), imshow(C2)
    colormap(gca, jet(256));caxis([-lim2 lim2]);
    
end

if S.idx3~=0
    
    A0 = axes;
    set(A0,'Parent',handles.img3Panel,'NextPlot', 'replacechildren');
    
    min_img3=min(min(min(S.img3)));
    max_img3=max(max(max(S.img3)));
    lim3= abs(mean([min_img3 max_img3]));
    subplot(3,1,3), imshow(A3)
    colormap(gca, jet(256));caxis([-lim3 lim3]);
    subplot(3,1,1), imshow(B3)
    colormap(gca, jet(256));caxis([-lim3 lim3]);
    subplot(3,1,2), imshow(C3)
    colormap(gca, jet(256));caxis([-lim3 lim3]);
    
end

S.firstPrint=0;

guidata(handles.h, S);

return